package droolscours

import droolscours.Account;
import droolscours.AccountingPeriod;
import droolscours.CashFlow;
import util.OutputDisplay;

global OutputDisplay showResult;

rule "Account group1"
    ruleflow-group "Group1"
    when
        Account(  )
    then 
        showResult.showText("Account in Group1");
end
rule "Account group2"
    ruleflow-group "Group2"
    when
        Account(  )
    then 
        showResult.showText("Account in Group2");
end